- front/src/app/(tabs)/log_in.tsx
- front/src/app/(tabs)/sign_up.tsx
- front/src/app/_layout.tsx
> ログインとサインアップ画面を追加

- back/src/helpers/requestHelper.ts
- back/src/prisma/schema.prisma
- back/src/routes/requests.ts
- front/src/app/(tabs)/followRequestList.tsx
- front/src/app/(tabs)/followerList.tsx
- front/src/components/FollowerListItem.tsx
> Reject follow request

- web/.eslintrc.cjs
- web/README.md
- web/src/App.tsx
- web/src/components/EditUserDialog.tsx
- web/src/components/Header.tsx
- web/src/main.tsx
- web/src/providers/AuthProvider.tsx
- web/src/routes/login.tsx
- web/src/routes/root.tsx
- web/src/routes/signUp.tsx
- web/src/routes/tabs/followers.tsx
- web/src/routes/tabs/home.tsx
- web/src/routes/tabs/profile.tsx
- web/src/routes/tabs/requests.tsx
- web/src/utils/getUserData.ts
- web/vite.config.ts
> /web をフォーマットした

- common/types.ts
- server/prisma/schema.prisma
- server/src/database/matches.ts
- server/src/database/requests.ts
> リレーションの名前を sending と receiving に修正

- server/src/routes/requests.ts
- web/src/api/request.ts
受け入れボタンを押したらrejectし、拒否ボタンを押したらacceptしていたので、修正しました
> Fix accerpt reject button

- web/src/routes/tabs/profile.tsx
> 編集が完了したら、自動的にリロードするようにした。

- web/src/api/hooks.ts
- web/src/routes/tabs/profile.tsx
useMe Hookを導入して、レンダリングされない問題を解決
> Profileタブでリロードしたら画面に表示されない問題を解決

- web/src/components/EditUserDialog.tsx
- web/src/components/PhotoPreview.tsx
- web/src/components/data/photo-preview.tsx
- web/src/firebase/store/upload-photo.ts
- web/src/index.css
- web/src/routes/signUp.tsx
- web/src/supabase/upload-photo.ts
> Photo Uploader の改善

- server/src/router/users.ts
- web/src/components/avatar/avatar.tsx
- web/src/components/chat/DMStack.tsx
- web/src/routes/tabs/chat.tsx
- web/src/routes/tabs/followers.tsx
- web/src/routes/tabs/home.tsx
- web/src/routes/tabs/profile.tsx
TODO
~idだけでアバターアイコンを表示できるように修正する~
アイコン取得のためだけに、もう一度リクエスト飛ばすのはアホらしいのでやめました。
> アバターコンポーネントを追加

- web/index.html
- web/src/components/avatar/avatar.tsx
- web/src/components/chat/DMStack.tsx
- web/src/components/chat/MessageInput.tsx
- web/src/components/chat/MessageWindow.tsx
- web/src/components/chat/Room.tsx
- web/src/components/chat/RoomHeader.tsx
- web/src/components/chat/RoomList.tsx
- web/src/components/chat/RoomWindow.tsx
- web/src/routes/tabs/chat.tsx
- web/src/routes/tabs/followers.tsx
- web/src/routes/tabs/home.tsx
- web/src/routes/tabs/profile.tsx
closes #108 
TODO
- edit機能と削除機能をつける
- ~開いた時にスクロールするように~
- スマホ版でもまともなUIにする
> ChatのUIを実装

- web/src/components/EditUserDialog.tsx
- web/src/components/PhotoPreview.tsx
> #124 の修正とデフォルトで以前の画像を表示する

- web/src/routes/root.tsx
tabのpathとlabelの順番が間違っていたので、それを修正
> tabのpathとlabelを修正

- server/src/database/requests.ts
- server/src/router/users.ts
- web/src/api/hooks.ts
- web/src/api/internal/endpoints.ts
- web/src/components/match/myRequests.tsx
- web/src/components/match/othersRequests.tsx
- web/src/components/match/requests.tsx
closes #134 
見た目などは別PRでまた調整します。
> 自分が送信したリクエストを見れるようにした

- web/src/components/ImageFallback.tsx
- web/src/components/avatar/WithFallback.tsx
- web/src/components/avatar/avatar.tsx
> image fallback

- compose.yml
- web/package-lock.json
- web/package.json
- web/src/components/ImageCropper.tsx
- web/src/components/PhotoPreview.tsx
- web/src/firebase/store/upload-photo.ts
> 画像を crop する

- Makefile
- compose.yml
> hot reload

- server/src/database/users.ts
- web/src/components/EditUserBox.tsx
- web/src/components/EditUserDialog.tsx
> Profile 編集画面が閉じられない問題と画像が勝手に消される問題を修正

- web/src/api/user.ts
- web/src/firebase/auth/lib.ts
> リロード時に認証情報が消えるエラーを修正した

- common/zod/methods.ts
- common/zod/schemas.ts
- common/zod/types.ts
- server/src/router/chat.ts
- server/src/router/users.ts
- web/src/components/EditUserBox.tsx
- web/src/components/PhotoPreview.tsx
- web/src/components/chat/MessageInput.tsx
> Zodでバリデーションを行った。(front、back含めて)

- server/src/database/chat.ts
- server/src/database/matches.ts
- server/src/database/requests.ts
- server/src/router/chat.ts
- server/src/router/users.ts
> 関数の命名の変更 (GET 系の関数を get*** に)

- Makefile
- web/src/firebase/auth/lib.ts
> getIdTokenを10回呼んでいたのを修正

- Makefile
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- web/eslint.config.js
- web/package-lock.json
- web/package.json
- web/src/api/user.ts
- web/src/components/EditUserBox.tsx
- web/src/components/chat/MessageInput.tsx
- web/src/components/chat/MessagePopup.tsx
- web/src/routes/signUp.tsx
- lint-staged を導入し、precommit 実行時に staging のファイルのみ lint / format されるようにしました (resolves #142)
> lint-staged を整備

- web/src/components/chat/MessageInput.tsx
parseMessageからparseContentに変更した
solve #194
> Zodのせいでメッセージ送れない問題を修正

- server/src/database/chat.ts
- server/src/database/client.ts
- server/src/database/courses.ts
- server/src/database/enrollments.ts
- server/src/database/matches.ts
- server/src/database/requests.ts
- server/src/database/users.ts
- server/src/firebase/auth/db.ts
- server/src/seeds/seed.ts
Prisma Client インスタンスをひとつに
Supabase との接続が Supabase 側の接続クライアント制限により、不安定になっていたため。
> 単一の Prisma Client インスタンスを使う

- .github/workflows/ci.yml
CI で Bun を使うようにした
CI の setup-node を setup-bun に置き換えた
ない
x
> CI で bun を使う

- web/src/components/course/CourseRegisterConfirmDialog.tsx
CourseTable を、削除と登録を同じ形でできるようリファクタリング
> CourseTable を削除に対応できるようリファクタリング

- web/src/components/course/CourseDeleteConfirmDialog.tsx
- web/src/components/course/SelectCourseDialog.tsx
登録した授業を削除する時に確認画面がなかったので追加しました。
deleteアイコンをクリック時の挙動を変更しました。
deleteアイコンクリック時の挙動以外特になし。
特になし
特になし
> 削除時に確認を追加しました。

- web/src/components/LogOutButton.tsx
- web/src/routes/editCourses.tsx
- web/src/routes/editProfile.tsx
- web/src/routes/tabs/settings.tsx
> Setting UI

- web/src/routes/login.tsx
- web/src/styles/login.css
> Make first page

- common/zod/schemas.ts
- server/prisma/schema.prisma
- server/src/database/courses.ts
- server/src/router/courses.ts
- server/src/seeds/insertCoursesFromJSON.ts
- web/src/components/course/CoursesTable/index.tsx
シ楽バス形式の JSON から CourseMate の DB の Course, Slot テーブルへの登録を行うスクリプトを追加
(セメスター毎に実行すればよい)
曜限として「月3」のようなものだけを想定していましたが、実データを見ると「集中」などが存在することが判明したため `day` と `period` の型を変更しました。
集中講義など「月3」のようなパターンに当てはまらない場合は
- `day` を `"other"` に
- `period` を `0` に
とするようにしました。
DB のスキーマが変更されたので更新が必要です。
> 授業をJSONからDBに追加するスクリプトを追加

- web/src/components/Card.tsx
> カードをスクロール可能に

- .cspell.json
- Makefile
`make dev-db`を実行することで、開発用のDBを作成できるようになった。
cspell
> 開発用のDBをコマンドで作成できるようになった。

- web/src/components/Card.tsx
- web/src/routes/tabs/settings.tsx
> 設定画面で授業側が出てるとき編集すると、授業の方を出すように

- web/src/routes/editCourses.tsx
- web/src/routes/editProfile.tsx
> edit画面のcssを修正

- web/src/components/config/PhotoPreview.tsx
- web/src/routes/registration/common.tsx
- web/src/routes/registration/steps/step2_img.tsx
- web/src/routes/registration/steps/step3_confirmation.tsx
- web/src/routes/registration/steps/step4_course.tsx
登録ボタンの見た目を修正
ボタンそのものの見た目を変更しただけで場所は変えてない。
> 登録ボタンの見た目を修正

- Makefile
- server/src/firebase/auth/lib.ts
- server/src/functions/user.test.ts
- test/fetcher.ts
- test/server.spec.ts
test を追加
unit test のサンプルを書いた
bun
> Write more test

- web/src/routes/editCourses.tsx
> 授業編集でflexboxを使うよう修正

- web/src/routes/editCourses.tsx
- web/src/routes/editProfile.tsx
- web/src/routes/tabs/settings.tsx
> h1 のセマンティクスを修正

- web/src/components/Card.tsx
> 性別があふれてるのの修正

- Makefile
> deploy 時に copy-common するように修正　

- server/src/seeds/insertCoursesFromJSON.ts
> 講義のJSONをDBに登録するスクリプトで教員を扱えるよう修正

- web/src/components/course/SelectCourseDialog.tsx
closes #314 
Dialog を fullwidth 指定
https://github.com/user-attachments/assets/1efe7eaa-7242-4859-9964-8ffefb71b33c
> 授業選択のモーダルが一定のサイズで表示されるよう修正

- web/src/components/course/CoursesTable/styles.module.css
> table と 黄色のマスとのズレを解消

- server/src/database/chat.ts
- as is:
- 誰かが Chat ページを開くたびにすべてのメッセージを取得している
- to be:
- take: 1, | LIMIT 1;
> リクエストのたびに全メッセージのフェッチをしない

- web/src/App.tsx
> リダイレクトにより登録ができない事象を一旦回避

- web/src/components/course/CoursesTable/index.tsx
> CourseTable のヘッダーがロード中に伸びる問題を解決

- .github/workflows/ci.yml
GitHub Actions の checkout のバージョンを v3 -> v4 にアップデート
同上
> update checkout from v3 to v4

- web/src/components/BanLandscape.tsx
- web/src/components/Card.tsx
- web/src/components/human/WithFallback.tsx
PCブラウザ版で崩れていたカード表面の表示を改善
close #309
Cardのビューの変更
上からそれぞれブラウザ版、Galaxy Z Fold 5、Iphone SEです
比較用現在のスマホ版(iPhone SE)
とくになし
とくになし
とくになし
> Cardの表面のブラウザ版表示の修正

- web/src/components/ImageFallback.tsx
- web/src/routes/registration/steps/step2_img.tsx
> fix url bug

- web/src/components/Card.tsx
> アバターのアイコンの大きさを修正

- web/src/routes/editCourses.tsx
- web/src/routes/editProfile.tsx
- web/src/routes/root.tsx
- web/src/routes/tabs/settings/aboutUs.tsx
- web/src/routes/tabs/settings/contact.tsx
- web/src/routes/tabs/settings/disclaimer.tsx
- web/src/routes/tabs/settings/profile.tsx
- web/src/routes/tabs/settings/settings.tsx
closes #378 
https://github.com/user-attachments/assets/d26238ed-7026-442e-a01e-50adc882ef53
> 設定画面の内容を修正した。

- .github/workflows/keep-alive.yml
> fix keep alive

- web/src/components/config/PhotoPreview.tsx
- web/src/routes/registration/steps/step1_profile.tsx
- web/src/routes/registration/steps/step2_img.tsx
- web/src/routes/registration/steps/step3_confirmation.tsx
- web/src/routes/registration/steps/step4_course.tsx
> 登録画面の UI を Figma に合わせる

- server/src/database/requests.ts
- server/src/router/requests.ts
- web/src/api/internal/endpoints.ts
- web/src/api/request.ts
- web/src/components/human/humanListItem.tsx
- web/src/components/match/myRequests.tsx
> リクエストをキャンセルする

- web/src/components/Card.tsx
- web/src/components/DraggableCard.tsx
- web/src/routes/tabs/home.tsx
Home画面のcssを修正しました。
close #374 
- ボタンサイズを大きくした
- 背景の切れていた部分の修正
- カードのwidthを大きくした
- カードのスワイプのthresholdを減少させた
https://github.com/user-attachments/assets/81875c78-3370-4081-8c26-be5ee90320a5
とくになし
とくになし
ブラウザ版横長画面のボタンが結構デカい
> Home画面のcssを修正

- web/src/components/human/humanListItem.tsx
> 名前が短いときに左端がずれる問題を修正

- web/src/routes/tabs/home.tsx
> Home画面でぐるぐるが左上にいくのを修正

- web/src/components/DraggableCard.tsx
- web/src/routes/tabs/home.tsx
Home画面のカードのスワイプ時に背景ではなくカードが変化するようにした
close #387 
https://github.com/user-attachments/assets/c7825c60-ff62-4781-aab7-6eea92fbd104
とくになし
とくになし
とくになし
> Home画面のカードのスワイプ時に背景ではなくカードが変化するようにした

- .cspell.json
- biome.json
- server/src/.gitignore
- web/src/components/chat/MessageInput.tsx
- web/src/routes/editProfile.tsx
ChatとeditProfileのauto completeを削除
closes #250 
ないはず
> Delete auto complete

- web/src/components/common/NavigateByAuthState.tsx
- web/src/firebase/auth/lib.ts
> fix firebase db desync

- web/src/routes/editProfile.tsx
> 設定画面の「授業編集へ」「プロフィール編集へ」のボタン高さ統一

- web/src/components/ImageCropper.tsx
> フロントで軽く圧縮してから送る

- web/src/components/config/PhotoModal.tsx
- web/src/components/config/PhotoPreview.tsx
- web/src/routes/editProfile.tsx
- web/src/routes/registration/steps/step2_img.tsx
> 画像クロップのモーダルを共通化

- web/src/components/course/components/CourseDeleteConfirmDialog.tsx
- web/src/components/course/components/CourseRegisterConfirmDialog.tsx
> 授業取得までの合間に「読み込み中...」を表示

- web/src/App.tsx
- web/src/routes/editProfile.tsx
- web/src/routes/registration/steps/step2_img.tsx
> SnackBarの位置を調整

- web/src/routes/tabs/home.tsx
> ホーム画面のカードとボタンを上下均等な位置に

- web/src/routes/editProfile.tsx
- web/src/routes/registration/steps/step1_profile.tsx
> スペースだけでの登録はできないように

- web/src/routes/login.tsx
close #288 
処理が終わるまで、Loadingしている
> 新規登録やlogin時にロードを追加して、戻された感じをなくした

- web/src/routes/tabs/home.tsx
Home画面で次のカードも表示されるように変更
close #338 
https://github.com/user-attachments/assets/a8a5458f-904a-42bc-9dd2-9166701794ed
Home画面の配置など
とくになし
ずれているのは意図的です
回転時にも見えるのちょっと変か？
> Home画面で次のカードも表示されるように変更

- web/src/components/course/components/SelectCourseDialog.tsx
授業IDがないと判別できないケースが多いため選択時に表示するようにした
src="https://github.com/user-attachments/assets/a3b97cbd-3059-4192-9b56-77358cfb7b49">
> v1.0.1 release

- web/src/components/chat/RoomWindow.tsx
> メッセージ編集中に ctrl + enter で確定する

- .github/workflows/keep-alive.yml
> keep-alive のスパンを 5 分から 2 分に短縮

- web/src/routes/tabs/settings/settings.tsx
> よくある質問をSettings画面にも追加した

- web/src/components/Header.tsx
> HeaderのCourseMateIconをクリックすると、/homeに飛ぶようにした

- web/src/firebase/auth/lib.ts
> cache token

- server/prisma/sql/recommend.sql
> HOME で REJECT した/された人を出さない

- Makefile
> prepare-deploy-server を修正

- lefthook.yml
- package-lock.json
- web/tsconfig.json
- Webのビルドのエラーが起きたので修正
- pre-commit hookで、[biome](biome: command not found)と言われたので、bunx biomeに変更
> ビルドエラーの修正とpre-commitのエラーの修正

- server/src/database/chat.ts
> チャットの並びをcreatedAtの時間で時系列順にした

- .github/workflows/rust.yml
> fix rust ci

- server/src/router/picture.ts
> fix JavaScript

- server/src/lib/socket/socket.ts
> add logging

- server/prisma/schema.prisma
> give read default(false)

- web/app/chat/layout.tsx
- web/app/friends/layout.tsx
- web/app/home/layout.tsx
- web/app/layout.tsx
- web/app/search/layout.tsx
- web/app/settings/layout.tsx
- web/components/BottomBar.tsx
- web/components/Header.tsx
> header, main, footerのCSSがちゃんと分けられるようになった。

- web/app/search/page.tsx
> search by course

- web/app/signup/common.tsx
- web/app/signup/page.tsx
- web/app/signup/steps/step1_profile.tsx
- web/app/signup/steps/step4_course.tsx
- web/app/signup/steps/step5_interests.tsx
> 初期登録で、興味分野を登録できるようになった。

- web/api/user.ts
- web/components/chat/RoomWindow.tsx
- web/hooks/useData.ts
チャット画面の軽微な修正
各メッセージの３点バーをメッセージの横に配置
メッセージ幅を画面の70%以内に制限
アルファベットのみの文でも文字が画面オーバーしないようにword-breakをbreak-allに変更
RoomWindowを使う範囲
- [☑️ ] 改めてセルフレビューしたか
- [☑️ ] 手動での動作検証を行ったか
- [☑️ ] server の機能追加ならば、テストを書いたか
- [ ☑️] 間違った使い方が存在するならば、それのドキュメントをコメントで書いたか
- [ ☑️] わかりやすいPRになっているか
> Message UI

- server/src/functions/engines/recommendation.ts
> fixed home not loading (i'm stupid)

- web/components/BottomBar.tsx
> BottomNavigationのアイコンを修正

- web/app/error.tsx
- web/app/home/page.tsx
- web/app/settings/card/page.tsx
- web/app/settings/courses/page.tsx
- web/app/settings/interests/page.tsx
- web/app/settings/profile/page.tsx
- web/app/signup/steps/step4_course.tsx
- web/app/signup/steps/step5_interests.tsx
- web/components/match/matching.tsx
- web/components/match/myRequests.tsx
- web/components/match/othersRequests.tsx
close #609 
エラーが発生したら、すべてapp/error.tsxの内容になるはず.
> 不要なerror.messageをすべて削除した。

- web/app/home/page.tsx
> fixed home showing "sent like to all" while loading

- web/app/settings/page.tsx
- web/app/tutorial/layout.tsx
> fixed format

- web/app/settings/delete/page.tsx
> center warning text in account deletion

- web/hooks/useCustomizedSWR.ts
- web/hooks/useData.ts
> useAuthorizedData と useCustomizedSWR のドキュメントを改善する

- web/components/course/components/CourseRegisterConfirmDialog.tsx
- web/components/course/components/SelectCourseDialog.tsx
- **make the modal easier to close**
- **fixed many flaws**
> fix settings/course

- web/app/settings/profile/page.tsx
> fix settings profile

- Makefile
> hack: remove frozen lockfile

- web/components/ImageFallback.tsx
> スマホ画面で、画像がダウンロードされている問題を解決

- bun.lock
- server/.env.sample
- server/package.json
- server/src/database/client.ts
- SQL のログを server のコンソールに出せるようにした
> SQL のログを出力

- server/src/index.ts
エラーハンドリングのミドルウェアを、一番下に書かないと動いていないようなので一番下に動かした
https://expressjs.com/en/guide/error-handling.html
> Express のエラーハンドリングを修正

- server/src/router/users.ts
> fix: get by id

- server/src/router/matches.ts
- server/src/router/picture.ts
- server/src/router/requests.ts
honoのContext関連のエラーが出ないようにした
returnを追加
特になし
特になし
特になし
> fix hono Context

- web/app/manifest.ts
> fix: theme color を白に

- server/prisma/sql/recommend.sql
> hotfix 4/14
