web/src/routes/root.tsx

ページがリロードされたときに useLocation フックが現在のパスを取得し、それに基づいて value が設定されるため、ナビゲーションの状態が維持され、Header部分がpathに従ったものになる

reloadしたらheaderがhomeになってしまう問題を解決

---

common/types.ts
server/src/database/users.ts
server/src/routes/users.ts
web/src/api/user.ts
web/src/components/EditUserDialog.tsx
web/src/routes/tabs/profile.tsx

- **fix the bug**
- **[type] make use of UpdateUser and InitUser. [rename] rename onClose -> close because it is expected to close the dialog [delete] delete prop userId in EditUserDialog because it doesn't need to be there**

unauthorized error と code smell を複数修正

---

web/src/components/ImageCropper.tsx
web/src/components/human/WithFallback.tsx
web/src/routes/registration/index.tsx
web/src/routes/registration/steps/step1.tsx
web/src/routes/registration/steps/step3.tsx

写真のクロップページの機能を実装
デフォルトのAvatarがあるなかで、写真をクロップすると、そのAvatarの部分が選択した写真になるようにした
透過画像をアップロードすると黒くなる問題を解決
特になし

写真のクロップページの機能を実装

---

web/src/components/BanLandscape.tsx
web/src/components/Card.tsx
web/src/components/DraggableCard.tsx
web/src/main.tsx

Card issue

---

web/src/components/config/PhotoPreview.tsx
web/src/routes/registration/steps/step2_img.tsx

アイコン設定画面の見た目をfigmaに合わせて変更
こんな感じにfigmaに合わせて変更
return内の<div></div>の範囲?区分?が少し変わっています。
「写真を追加」ボタンだけmax-widthで最大値が設定されています。

アイコン設定画面の見た目をfigmaに合わせて変更

---

web/src/components/config/PhotoPreview.tsx
web/src/routes/registration/steps/step2_img.tsx

#271
写真選択ボタンの当たり判定がラベルとボタンが離れてた？ので、step2ではなく、Photopreviewで位置を調整するように変更した。
特になし

写真選択ボタンの当たり判定の修正

---

web/src/api/internal/fetch-func.ts
web/src/components/ImageCropper.tsx
web/src/components/config/PhotoPreview.tsx
web/src/routes/editProfile.tsx
web/src/routes/registration/steps/step2_img.tsx

close #326, close #327
画像のアップロード機能の改善
- 選択した画像のファイルサイズが大きすぎると、空のダイアログが開く
- クロップ後の画像のファイルサイズのバリデーションはせず、サーバーに弾かれると暗黙に失敗する
- 画像を一回選択したら確定以外何もできない
- 選択した画像のファイルサイズによるブロックはしない
- クロップ後の画像のファイルサイズを事前にチェックする
- 画像を選択した後も閉じることが可能
なし
フロントエンドでの画像の圧縮 (5MB 以下にしたい)
- 理由: server の機能追加ではない
- 理由: 間違った使い方は存在しない

画像アップロード機能の改善

---

server/src/database/picture.ts
web/src/components/ImageFallback.tsx

closes #356 
同じデータベースを使う複数のサーバーのうち一つで画像を変更すると、URL がぞのサーバーに固定される問題を修正
差分見ろ。
画像の URL のフォーマットが変わる。
画像の更新が必要

同じデータベースを使う複数のサーバーのうち一つで画像を変更すると、URL がそのサーバーに固定される問題を修正

---

web/src/components/human/humanListItem.tsx

Friendsメニューでアイコンのクリックでしかカードが開けなくなっていたが、ListItemの全体をクリックできるようにした
close #311 
Buttonの適用範囲とスタイルの変更
とくになし
とくになし
とくになし

FriendsメニューでListItemの任意の場所のクリックでカードを開けるようにした

---

common/zod/schemas.ts
web/src/components/chat/MessageInput.tsx
web/src/components/chat/RoomWindow.tsx

チャット画面で改行が可能になった

---

web/src/routes/root.tsx

タブレット・PC ではヘッダーの縦幅がやや大きくなるが、それが考慮されていなかったためメインコンテンツとヘッダーとの隙間がなくなっていた。これを修正した。
Before
https://github.com/user-attachments/assets/77bf4c91-ea76-42b0-bfdf-fffcf03c2e0c
After
https://github.com/user-attachments/assets/d8f1e33a-7eae-4802-a262-a1467271c142

タブレット・PC でヘッダーとの隙間がなくなる現象を解消

---

web/src/components/Card.tsx

「その他」などと表示され何のことかわからないので「性別」「学年」などのラベルをつけた。
あとはデザイン的にちょっとスカスカしていたのでなんか入れるとちょっと見栄えが良くなるかもという。
長い場合
短い場合
カード内

カードに「学部」「性別」などのラベルを追加

---

web/src/components/Card.tsx
web/src/components/DraggableCard.tsx
web/src/components/course/components/CoursesTableCore/index.tsx
web/src/components/course/components/CoursesTableCore/styles.module.css
web/src/routes/root.tsx
web/src/routes/tabs/home.tsx
web/src/routes/tabs/settings/profile.tsx

カード関連のスタイルを調整しました。
- 画面の縦の大きさ基準でカードのレイアウトを固定するようにしました。
- カードに「学部」「性別」などのラベルを追加しました。
https://github.com/user-attachments/assets/da98e086-cda1-4b87-a8ee-475a5112e05a
- close #239 
- カードごと小さくなったので close #377 
カード内部。また、カードの幅に依存するものには影響があるかもしれない
各 PR を Squash and Merge してこの PR を作ったので、それぞれの詳細は各 PR を参照してください。

ホーム画面のカード周りのスタイルを調整

---

web/src/routes/tabs/settings/aboutUs.tsx
web/src/routes/tabs/settings/components/TopNavigation.tsx
web/src/routes/tabs/settings/contact.tsx
web/src/routes/tabs/settings/disclaimer.tsx
web/src/routes/tabs/settings/profile.tsx

- Setting 画面の上部のナビゲーションを共通化した。
- 「あなたのカード」画面の構成を修正した。
- close #436
Setting 画面。

Setting 画面のスタイルを修正

---

web/src/components/course/components/SelectCourseDialog.tsx

授業IDがないと判別できないケースが多いため選択時に表示するようにした

授業IDを選択時に表示

---

Makefile
server/.env.sample
server/src/index.ts
server/src/lib/utils.ts

SERVER_ORIGIN, WEB_ORIGIN, WEB_ORIGIN_BUILD etc の代わりに CORS_ALLOW_ORIGINS を使う

---

web/app/chat/page.tsx
web/firebase/auth/lib.ts

Next移行に伴う、リロード問題を解決

---

web/components/Card.tsx

CardをDaisyUIに移行
見た目上は特になし
とくになし
とくになし
とくになし

CardをDaisyUIに移行

---

web/app/home/page.tsx

homeのdaisyUI対応
Homeのカードの配置がわずかに移動
とくになし
とくになし
とくになし

homeのdaisyUI対応

---

.github/workflows/ci.yml
web/api/chat/chat.ts
web/app/chat/[id]/page.tsx
web/app/chat/page.tsx
web/components/chat/MessageInput.tsx
web/components/chat/RoomHeader.tsx
web/components/chat/RoomList.tsx
web/components/chat/RoomWindow.tsx
web/firebase/auth/lib.ts
web/next.config.mjs

close #521 
app/chat/[id]/page.tsxにおいて、処理をhookにまとめる必要があるが、なんかうまくいかなかったので、放置してる
あと、型とかやばそう

/chat/:idにアクセス可能に

---

web/app/home/page.tsx
web/components/DraggableCard.tsx

ハート要素を削除した

---

common/zod/schemas.ts
server/src/database/chat.ts
server/src/functions/chat.ts
server/src/router/chat.ts
web/api/chat/chat.ts
web/app/chat/[id]/page.tsx
web/components/chat/RoomList.tsx
web/components/chat/RoomWindow.tsx
web/components/human/humanListItem.tsx

close #499 
- ユーザーがリクエストを送ると、マッチングしてなくてもチャットはできる状態となる
- この時、このユーザーをacceptしますか？というモーダルが常にチャット欄に出て、YESだったら、そのモーダルは消えてチャット可能、NOだったら、チャットは消える。
サーバー側で、リクエストに関する制限を緩めた。

リクエストを送ったら、チャットでメッセージが送れるようになる

---

Makefile
flake.nix

lefthook install が実行されないのを修正

---

web/app/settings/notification/page.tsx
web/app/settings/page.tsx

close #298 
管理者画面を作ろかと思ったが、管理者画面を作ってメンテナンスするコストを考えると、とりあえず直書き運用でいい気がした #540 

お知らせページを追加 運用はコードを直書き

---

server/src/database/chat.ts
server/src/functions/chat.ts
server/src/router/chat.ts
web/api/internal/endpoints.ts
web/components/chat/RoomWindow.tsx
web/components/data/socket.ts
web/lib/utils.ts

fixed websocket

---

web/components/human/humanListItem.tsx
web/components/search/table.tsx

検索画面から、リクエストを送れるようになった

---

server/src/index.ts
server/src/lib/cross-origin/share.ts
server/src/lib/socket/socket.ts

fix websocket not working on render

---

server/prisma/schema.prisma

Cascade Interest on InterestSubject Delete

---

Makefile

remove: prisma exec

---

common/zod/schemas.ts
server/src/firebase/auth/lib.ts
test/server.spec.ts
web/api/internal/fetch-func.ts
web/firebase/auth/lib.ts

hotfix: cannot authorize

---

web/app/home/page.tsx

closes #664 
Home画面のユーザー取得時に<FullScreenCircularProgress />が出ないようにし、代わりに<NoMoreUsers />が表示されるようにした。

Homeでユーザー取得時にloading画面にする

---

web/app/signup/steps/step1_profile.tsx
web/app/signup/steps/step2_img.tsx
web/app/signup/steps/step3_confirmation.tsx
web/app/signup/steps/step4_course.tsx
web/app/signup/steps/step5_interests.tsx

Confirmation UI

---

web/components/BottomBar.tsx

set safe area

---

web/app/chat/components/RoomList.tsx
web/app/friends/page.tsx
web/app/home/components/NoMoreUser.tsx
web/app/home/page.tsx
web/app/search/page.tsx
web/components/common/BackgroundText.tsx
web/components/match/matching.tsx
web/components/search/search.tsx

本当は授業やタグでのフィルタもしようと思ったが一応引っかかるのでいいことにした

検索で1文字入力してからユーザを表示
